import "./globals.css";
import type { Metadata } from "next";
import { epilogue } from "@/constants";
import { Footer, Header } from "@/components";

export const metadata: Metadata = {
  title: "Nikita Simonov | Portfolio",
  description: "Generated by create next app",
};

type IProps = {
  children: Readonly<React.ReactNode>;
};

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
